# Agentic Brain Framework Configuration

# Default agent to use
default_agent: "claude"

# Agent configurations
agents:
  claude:
    type: "claude"
    model: "claude-3-opus-20240229"
    temperature: 0.7
    max_tokens: 4096
    top_p: 0.95
    system_prompt: |
      You are an AI assistant integrated with the CTM-AbsoluteZero framework, 
      a self-learning system that combines Continuous Thought Machine and Absolute Zero Reasoner 
      paradigms. You help generate tasks, analyze solutions, and provide insights 
      across various domains including quantum computing, maze solving, and sorting algorithms.
      
      When asked to generate a task, make sure it's appropriately challenging based on the 
      current skill level and includes all necessary parameters for execution.
      
      Always provide your responses in the requested JSON format when asked to.

  deepseek:
    type: "deepseek"
    model: "deepseek-chat-32k"
    temperature: 0.8
    max_tokens: 4096
    top_p: 0.95
    # DeepSeek API is approximately 80x cheaper than Claude API
    # $0.0001/1k tokens vs $0.008/1k tokens

# DFZ integration configuration
dfz:
  dfz_path: "../evolution"  # Relative path to DFZ installation
  plugin_enabled: true
  model_sync_interval: 600  # 10 minutes
  conversation_history_size: 50
  task_registry_size: 1000

# Domain configurations
domains:
  quantum:
    min_qubits: 2
    max_qubits: 20
    algorithms: ["vqe", "grover", "qft"]
    default_noise: 0.01
    max_circuit_depth: 10
  
  maze:
    min_size: [5, 5]
    max_size: [50, 50]
    complexity_levels: ["easy", "medium", "hard", "extreme"]
    default_complexity: "medium"
  
  sorting:
    min_array_size: 10
    max_array_size: 10000
    algorithm_types: ["comparison", "counting", "distribution"]
    default_algorithm: "comparison"

# Task generation configuration
task_generation:
  max_difficulty: 10
  difficulty_progression_rate: 0.1
  novelty_weight: 0.3
  challenge_weight: 0.5
  domain_rotation: true  # Rotate through domains
  domain_weights:
    quantum: 0.4
    maze: 0.3
    sorting: 0.3

# Solution analysis configuration
solution_analysis:
  effectiveness_weight: 0.3
  efficiency_weight: 0.3
  correctness_weight: 0.4
  min_strengths: 2
  min_weaknesses: 1
  min_suggestions: 2

# Reward system configuration
reward:
  base_scale: 10.0
  novelty_bonus: 2.0
  efficiency_bonus: 1.5
  correctness_bonus: 2.0
  difficulty_multiplier: 0.2  # Additional reward per difficulty level
  exploration_bonus: 1.0
  failure_penalty: -2.0

# Logging configuration
logging:
  level: "info"
  file: "logs/agentic_brain.log"
  rotation: true
  max_size: 10485760  # 10 MB
  backup_count: 5

# Performance optimization
performance:
  cache_embeddings: true
  cache_duration: 3600  # 1 hour
  parallel_execution: true
  max_workers: 4