# Configuration par défaut pour CTM-AbsoluteZero

ctm:
  model_path: "models/ctm_base"
  device: "cuda"
  precision: "float16"
  max_batch_size: 32

absolute_zero:
  w_solve: 0.5
  w_propose: 0.3
  w_novelty: 0.1
  w_progress: 0.1
  solve_success_threshold: 0.6
  learnability_target_success_rate: 0.5

ppo:
  learning_rate: 3.0e-6
  batch_size: 16
  mini_batch_size: 4
  ppo_epochs: 4
  clip_range: 0.15
  target_kl: 0.015