# Production configuration for CTM-AbsoluteZero

# Agent configuration
agent:
  proposer_model_path: "models/proposer"
  proposer_tokenizer_path: "models/proposer"
  solver_model_path: "models/solver"
  solver_tokenizer_path: "models/solver"
  max_tokens: 2048
  temperature: 0.7
  top_p: 0.95
  task_history_size: 100
  max_attempts: 3
  timeout: 60

# CTM interface configuration
ctm:
  interface_type: "real"
  connection_timeout: 30
  retry_count: 3
  components:
    - "maze_solver"
    - "image_classifier"
    - "quantum_sim"
    - "sorter"
  metrics_enabled: true

# Reward system configuration
rewards:
  embedding_dim: 768
  novelty_threshold: 0.2
  skill_levels: 5
  hyperparams:
    novelty_weight: 0.3
    progress_weight: 0.3
    success_weight: 0.3
    efficiency_weight: 0.1
    max_reward: 10.0
    min_reward: -5.0

# Transfer learning configuration
transfer:
  adapter_type: "neural"
  adaptation_rate: 0.2
  transfer_threshold: 0.7

# Phase controller configuration
phase:
  phase_duration: 7200  # 2 hours
  initial_phase: "exploration"
  phases:
    exploration:
      solve: 0.4
      discover: 0.6
    exploitation:
      solve: 0.8
      discover: 0.2
    transfer:
      solve: 0.5
      discover: 0.5

# Available domains
domains:
  - "maze"
  - "vision"
  - "quantum"
  - "sorting"
  - "general"

# Logging configuration
logging:
  level: "info"
  file: "logs/ctm-az.log"
  rotation: true
  max_size: 10485760  # 10 MB
  backup_count: 5
  metrics_interval: 300  # 5 minutes

# Data storage configuration
storage:
  data_dir: "data"
  embeddings_dir: "data/embeddings"
  model_dir: "models"
  state_dir: "state"
  backup_enabled: true
  backup_interval: 3600  # 1 hour

# DFZ integration configuration
dfz:
  dfz_path: "../evolution"  # Relative path to DFZ installation
  plugin_enabled: true
  model_sync_interval: 600  # 10 minutes
  conversation_history_size: 50
  task_registry_size: 1000

# Performance configuration
performance:
  batch_size: 16
  parallel_execution: true
  max_workers: 4
  memory_limit: 8192  # MB
  cuda_enabled: true
  fp16: true
  cpu_threads: 8

# Development options (disable in production)
development:
  debug_mode: false
  trace_execution: false
  mock_components: false