# Configuration spécifique pour les tâches quantiques

ctm:
  model_path: "models/ctm_quantum"
  device: "cuda"
  precision: "float16"
  max_batch_size: 16
  quantum_backend: "simulator"  # options: simulator, qiskit, pennylane

absolute_zero:
  w_solve: 0.6
  w_propose: 0.2
  w_novelty: 0.1
  w_progress: 0.1
  solve_success_threshold: 0.5
  learnability_target_success_rate: 0.6

ppo:
  learning_rate: 2.0e-6
  batch_size: 8
  mini_batch_size: 2
  ppo_epochs: 6
  clip_range: 0.1
  target_kl: 0.01

quantum:
  max_qubits: 10
  noise_models:
    - depolarizing
    - amplitude_damping
    - phase_damping
  algorithms:
    - vqe:
      max_iterations: 100
      optimizer: "COBYLA"
    - grover:
      oracle_type: "bit_pattern"
      iterations: "auto"
    - qft:
      approximation: True
      approximation_degree: 0.01